apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: echo-sink
  labels:
    strimzi.io/cluster: my-connect
spec:
  class: EchoSink
  tasksMax: 1
  autoRestart:
    enabled: true
  config:
    topics: "my-topic"
    fail.task.after.records: 5
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.storage.StringConverter
    key.converter.schemas.enable: false
    value.converter.schemas.enable: false